### ISSUE TITLE
Update: Uses deprecated/broken dependency

### ISSUE THREAD

**Issue by GingerAdonis** [Necktrox/mta-discord-bot#1]
Discord.js has been updated and this project uses a deprecated version which seems to be broken for me (worked fine before).

I might fork it and update it myself. Although I'm also fine if you want to update it @Necktrox

**Comment by Necktrox** [comment]
I will update the discord.js library.

**Comment by Necktrox** [comment]
@JarnoVgr Does the code update work?

**Comment by GingerAdonis** [comment]
Seems to work. Thank you very much! :)
